// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efnrvnxfmzmluexucvgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmbnJ2bnhmbXptbHVleHVjdmdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MjA3ODgsImV4cCI6MjA1ODE5Njc4OH0.bnkEZjDHVB6Zs7mY9u9yMdZyHzlNDRDWqLyJze3Yg1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);